### ISSUE TITLE
Undefined Apply and classRuleSettings

### ISSUE THREAD

**Issue by cristian-araujo** [proengsoft/laravel-jsvalidation#726]
### Subject of the issue
appears this two errors 
```
jsvalidation.js:34 Uncaught TypeError: Cannot set property 'classRuleSettings' of undefined
Uncaught TypeError: Cannot read property 'apply' of undefined
```

### Your environment
* version of this package: 4.4.6
* version of Laravel: 8.55.0

**Comment by bytestream** [comment]
what browser are you using?

**Comment by cristian-araujo** [comment]
> what browser are you using?

Opera but it appears in Chrome and Firefox too

**Comment by bytestream** [comment]
Please provide a project / website which reproduces the issue

**Comment by cristian-araujo** [comment]
I dont have an online website but here is the complete error, if you need more information I can provide it.

```
jsvalidation.js:34 Uncaught TypeError: Cannot set property 'classRuleSettings' of undefined
    at Object.init (jsvalidation.js:34)
    at HTMLDocument.<anonymous> (jsvalidation.js:382)
    at j (jquery.js:3094)
    at Object.fireWith [as resolveWith] (jquery.js:3206)
    at Function.ready (jquery.js:3412)
    at HTMLDocument.I (jquery.js:3428)
base.js:5924 jQuery.Deferred exception: Cannot read property 'apply' of undefined TypeError: Cannot read property 'apply' of undefined
    at jQuery.fn.init.$.fn.validate (http://opc.local:50/vendor/jsvalidation/js/jsvalidation.js:2341:32)
    at HTMLFormElement.<anonymous> (http://opc.local:50/registration:154:21)
    at Function.each (http://opc.local:50/js/base.js:2259:19)
    at jQuery.fn.init.each (http://opc.local:50/js/base.js:2081:17)
    at HTMLDocument.<anonymous> (http://opc.local:50/registration:153:33)
    at mightThrow (http://opc.local:50/js/base.js:5640:29)
    at process (http://opc.local:50/js/base.js:5708:12) undefined
jQuery.Deferred.exceptionHook @ base.js:5924
base.js:5933 Uncaught TypeError: Cannot read property 'apply' of undefined
    at jQuery.fn.init.$.fn.validate (jsvalidation.js:30)
    at HTMLFormElement.<anonymous> (registration:154)
    at Function.each (base.js:2259)
    at jQuery.fn.init.each (base.js:2081)
    at HTMLDocument.<anonymous> (registration:153)
    at mightThrow (base.js:5640)
    at process (base.js:5708)
```

**Comment by cristian-araujo** [comment]
I still have this problem, I will try make an env for reproduce this.
