### ISSUE TITLE
How do we use the remote Validation with a Form Request?

### ISSUE THREAD

**Issue by jonnywilliamson** [proengsoft/laravel-jsvalidation#85]
Hi, I've just upgraded from an old version to the latest today (but I have ensured the latest files are in use and republished etc) and I'm very confused how to utilise the ajax validation on rules like `unique` or `exists`.

Firstly, everything was working! 

I know what this package does and I haven't had any issues. If I also change the new config option `disable_remote_validation` to true, my form works perfectly again.

However, I'd like to take advantage of the new ajax validation this package provides!

Could someone tell me what I'm supposed to be doing.

In my routes file, I have this:

``` php
//routes.php
Route::get('/', ['uses' => 'RegisterTelegramController@register']);
Route::post('/', ['as' => 'processRegistration', 'uses' => 'RegisterTelegramController@processRegistration']);
```

This shows my registration form, and processes the form once it is POSTED.

My `processRegistration()` method that deals with the POSTED data, uses a `FormRequest` for the validation.:

``` php
//RegisterTelegramController.php

    public function processRegistration(RegisterTelegramId $request)
    {
        //Member WILL exist because validation form has checked.
        //Add users registration details to database.
        //Return success message
    }
```

My form request is simple:

``` php
//FormRequest called RegisterTelegramId.php
<?php namespace App\Http\Requests;

class RegisterTelegramId extends Request
{

    public function rules()
    {
        return [
            'username' => 'required|exists:ibf_members,members_l_username',
            'password' => 'required',
            'telegramId' => 'required|digits_between:8,11'
        ];
    }
}
```

My html form, is simple (I've removed ALL styling and non useful info).

``` html
<!DOCTYPE html>
<body>
{!! Form::open(['route'=>'processRegistration', 'id' => 'tgregister', 'role' => 'form']) !!}
<input type="text" name="username" value="{{ old('username') }}">
<input type="password" name="password">
<input type="text" name="telegramId" value="{{ old('telegramId') }}">
<button type="submit">Submit</button>
{!! Form::close() !!}

{!! JsValidator::formRequest('App\Http\Requests\RegisterTelegramId', '#tgregister') !!}
</body>
</html>
```

So this all works fine when I DON'T use the ajax validation.

When I do use ajax validation, and say for example I put a value in the username field and tab to the next field, a POST request is sent to the form URL with the following parameters:

`username=joebloggs&_jsvalidation=username`

However my server returns a server 500 error - as I assume it doesn't know how to respond to this POST request.

What am I missing? What should my `processRegistration()` method in my controller be doing when it gets that ajax request?

Any help would be much appreciated.

**Comment by torrentalle** [comment]
Your example is working in my enviroment.
Can you post the error message from log file?

**Comment by jonnywilliamson** [comment]
So, I've been playing with the error logs and found this:

>[2015-10-05 22:17:51] development.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function decrypt() on null' in /hom
e/vagrant/Code/<snip>/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:84



So it instantly occurred to me. The POST request is not sending the `csrf_token`.

Even though it is set in my form (Because I use the Form Facade, it gets set automatically) and I verify that by also looking at the source code, when the POST is sent, it's not included.

Therefor Laravel throws a 500 server error.

I've got around the problem by adding the `processRegistration` route to the `app/Http/Middleware/VerifyCsrfToken.php` file in the `except` array.

That makes, it work, but I'd rather fix it by sending the token. How are you doing it?

**Comment by torrentalle** [comment]
the `csrf_token` should be send encripted in a **X-XSRF-TOKEN** request header. Can you check if is included in the `laravelValidationRemote`rule code generated by *JsValidation*?

```js           
 rules: {
     "username":{
          "laravelValidation":[["Required",[],"The username field is required.",true]],
          "laravelValidationRemote":[["Exists", ["username","eyJpdiI6IjNoanVUSkI1cEFLU3RwMDhTUUNpeEE9PSIsInZhbHVlIjoicDZxamk3bnR6MVU0RjYwblc0WlwvaEVuMUtnZ3JGUkxRR28yWjJmM0NpRWEzMTVWWE9KdVo3VTkzVkZwNFNFTHluNklCUjkrUTJmR3ZjVUI4QUVjcWlnPT0iLCJtYWMiOiJhYzFkZDYwZDYyNDAzN2JhYzgxMTI2OWJiMDBiN2U4NzZkN2ZmZjEyMDVjZDU1MGJlNTQxNzZkYTQ3NGNhYzkyIn0="],"The selected username is invalid.",false]]
     },
     "password":{
          "laravelValidation":[["Required",[],"The password field is required.",true]]
     },
     "telegramId":{
          "laravelValidation":[["Required",[],"The telegram id field is required.",true],["DigitsBetween",["8","11"],"The telegram id must be between 8 and 11 digits.",false]]
     }
}        


```

**Comment by jonnywilliamson** [comment]
Well this is confusing.

I removed the URL from the verifycsrf except array.

Here's the post request when I tried typing something into the username field:

```
POST / HTTP/1.1
Host: messages.dev:8000
Connection: keep-alive
Content-Length: 35
Pragma: no-cache
Cache-Control: no-cache
Origin: http://messages.dev:8000
X-XSRF-TOKEN: eyJpdiI6Im0zN0JpZ0pzZDBGYm5PSmRPeDZkM2c9PSIsInZhbHVlIjoiNUZxTUZzcEFnWmtqU2V2OHA1aHNleWV5UDROTWZPNWIrT2NiUGdcL0xTY1RRUDVOTXZuN1BqZmRpY1VJWExLSHFKelRtb2dqK3h4SUVpNGVqMTZZd2F3PT0iLCJtYWMiOiI4NzhlYjRkN2Y2NTIwZGU5ZGMwNzhjM2MwNDNkMmFjMmE2OTVmNTYxYjNmMzljNDdmNDY3ZGQyYzAzMDNjNjU1In0=
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
X-FirePHP-Version: 0.0.6
DNT: 1
Referer: http://messages.dev:8000/
Accept-Encoding: gzip, deflate
Accept-Language: en,en-GB;q=0.8
Cookie: XDEBUG_SESSION=PHPSTORM; XSRF-TOKEN=eyJpdiI6InVITkNjMjBpOTBPMGozdzlNVlBNU3c9PSIsInZhbHVlIjoiVWdQbHlcL1ZDVFpcLzR1VGdvSFJSQXJ2VFhmR1RBYlVDY0tvdmVMdkVQd1k1ZkxsZUNoRGhkekxsVFk1Q2FpR0NsZ3EwbmJMTitxUEJydVdOM0Vkd2RlUT09IiwibWFjIjoiMjRhNWZmNjViNGZmZGNlNWMwMjJhMDcxZDAzYTNmMDc0YWVjNmRlOGE0YWVkZGQ3MjA2YjZmNTY5NDdlZGU0MSJ9; laravel_session=eyJpdiI6ImgrSHZ6XC9lelR6RjJxcTY5Ym4yK2lnPT0iLCJ2YWx1ZSI6IktnR2RaekVON3RnTWNPcUdDcnJUcEg3NUp0YlhFZWZ0S21WaFBOR1ZcL3VjMVNyXC9GMjUzUld3OVJhQU1LTmFidkcybFRCYTQ5MHBtVTdWNGRCZitKcnc9PSIsIm1hYyI6ImYyZjkzYzRjYjg5NmEwMGE1NTZkMmE5NTQ4ZjIzNTBjNzcyM2IwYjdjNjA0ODVlMjRmYzc1ZDA2NmFlNDFjZjUifQ%3D%3D
```

2 different tokens?


This was the data posted
```
username=jonathan&_jsvalidation=username
```

Yet I got an instant 500 error message back.


Here's the Log file.

```
[2015-10-05 23:23:00] development.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function decrypt() on null' in /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:84
Stack trace:
#0 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct('???', '???', '???', '???', '???', '???', '???', '???')
#1 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError('???', '???')
#2 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(49): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->tokensMatch('???')
#4 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle('???', '???')
#5 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('???', '???')
#6 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('???')
#7 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\View\Middleware\ShareErrorsFromSession->handle('???', '???')
#8 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('???', '???')
#9 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('???')
#10 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle('???', '???')
#11 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('???', '???')
#12 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('???')
#13 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle('???', '???')
#14 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('???', '???')
#15 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('???')
#16 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle('???', '???')
#17 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('???', '???')
#18 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('???')
#19 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle('???', '???')
#20 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}('???', '???')
#21 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}('???')
#22 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}('???', '???')
#23 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then('???')
#24 /home/vagrant/CodeProjects/myurl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter('???')
#25 /home/vagrant/CodeProjects/myurl/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle('???')
#26 /home/vagrant/CodeProjects/myurl/public/index.php(0): {main}()
#27 {main}  
```

Thank you for your time and help with this.

As I say, it works as soon as I drop the csrf check....

**Comment by jonnywilliamson** [comment]
A-ha!!!

Found the bug!


The [Laravel docs state](http://laravel.com/docs/5.1/routing#csrf-x-xsrf-token):

![image](https://cloud.githubusercontent.com/assets/2513663/10302365/9f87eb46-6c03-11e5-91ba-ffa175f61f63.png)


If we look at the code in [jsvalidation.js around line 2231](https://github.com/proengsoft/laravel-jsvalidation/blob/master/public/js/jsvalidation.js#L2231-L2235)

```js
                beforeSend: function (xhr) {
                    if ($(validator.currentForm).attr('method').toLowerCase() !== 'get' && token) {
                        return xhr.setRequestHeader('X-XSRF-TOKEN', token);
                    }
                }
```

Notice the misspelling. Larvel expects
`X-CSRF-TOKEN` not
`X-XSRF-TOKEN`

Once I changed the X to a C everything is working!

Will I submit a PR?

**Comment by jonnywilliamson** [comment]
I'm back to errors again.

Something is incorrect between the token value that gets detected and set by jsvalidation from the sessionstore, and what is send along with the ajax request.

i.e. The script is sending the encrypted `_token` value from the form as a XSRF header when it should be non encrypted token sent as a CSRF header.

Or the script is sending the incorrect XSRF value.

Something isn't right but I'm not smart enough to work out which.

**Comment by torrentalle** [comment]
I'm preparing a new branch to get the csrf token from cookie, _csrf input or meta to avoid this issue

**Comment by torrentalle** [comment]
I think that I resolved the issue bu I can't reproduce it. Finally I get csrf token from Laravel while the javascript is rendering to avoid mistmatch tokens.
I have tryed to get token from cookie but I had some probles dealing with cookie path.

Can you try the release `dev-issue-85` and chek if it's working in your enviroment?

**Comment by jonnywilliamson** [comment]
Hello,

I'm just back from being away for a few days and have tried branch `issue-85`, without success.

After looking at your code changes I am still confused as to what you are doing, so excuse me if I go over things slowly so as I can understand and help work this out.

When you generate the rules for inserting into the view, the `RemoteValidation` trait is used.

During this execution, the `sessionStore` and `encrypter` are injected into the method `setSession`.

At a later stage, the function `getToken()` is called. It looks like this:
```php
    /**
     * Get csrf token used in Ajax Validations
     *
     * @return string
     */
    protected function getToken() {
        $token = $this->sessionStore->getToken();
        if (!is_null($this->encrypter)) {
            $token = $this->encrypter->encrypt($token);
        }

        return $token;
    }
```

From what I can see, you get the UNencrypted token from the session store and then encrypt it with the encrypter.

This is then returned to the view and displayed as a rule when the form loads.

Am I right so far?

Then when the user enters a character in the remote validation input field, the follow `javascript` gets fired:

```js
$.validator.addMethod("laravelValidationRemote", function (value, element, params) {

            var implicit = false,
                check = params[0][1],
                attribute = check[0],
                token = check[1];
// So token has been passed into this function and is in ENCRYPTED format

<snip code>

            $.ajax( $.extend( true, {
                mode: "abort",
                port: "validate" + element.name,
                dataType: "json",
                data: data,
                context: validator.currentForm,
                url: $(validator.currentForm).attr('action'),
                type: formMethod,

                beforeSend: function (xhr) {
                    if ($(validator.currentForm).attr('method').toLowerCase() !== 'get' && token) {
                        return xhr.setRequestHeader('X-XSRF-TOKEN', token);
                    }
                }
```

So here we see if the form method is NOT a GET and we have a TOKEN, then we set a `X-XSRF-TOKEN` header before we send the ajax.


So we are sending an encrypted CRSF token from the session store as a `X-XSRF-TOKEN` header.


If I look at the Laravel `VerifyCsrfToken.php` middleware,  here's the function that decodes a token and checks to see if it matches.

```php
    /**
     * Determine if the session and input CSRF tokens match.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    protected function tokensMatch($request)
    {
        $token = $request->input('_token') ?: $request->header('X-CSRF-TOKEN');

        if (! $token && $header = $request->header('X-XSRF-TOKEN')) {
            $token = $this->encrypter->decrypt($header);
        }

        return Str::equals($request->session()->token(), $token);
    }
```

So we can see, if there's a `_token` input OR a `X-CSRF-TOKEN` header we just check that against the session token. (Note there is NO decryption taking place.)

If there is an `X-XSRF-TOKEN` header, we DO try and decrypt it.

For whatever reason, this is problem I am having. Everytime the token attempts to be decrypted, I get this exception

`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function decrypt() on null' in /hom
e/vagrant/CodeProjects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:85`

I don't understand why it can't decrypt it!

I'll do some more investigating.

**Comment by jonnywilliamson** [comment]
Ahhhhhh.

OK, hands up. It looks like this is my fault.

I went sniffing around the the `Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php` file, trying to work out why the `$this->encrypter` was always null.

That led me to `App\Http\Middleware\VerifyCsrfToken.php` which extends the `Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php` class.

I had added an some extra setup code in the subclass `__construct()` method. But I had forgotten to call the `parent::__construct()` with this code. This meant that `Encrypter` was never injected properly into the class and so I was never able to decrypt any string or header.

What an annoying bug. I'm sorry I've only just discovered this myself. I hope I didn't waste much of your time.



Can I ask a couple of questions though:

Why do you get the token from a `sessionStore` and not make life easy by getting it directly from the form using the jsvalidation.js file?

Eg. For the past week this is how I was working around this problem, and it was working really well.

In js I added:

```js
$.validator.addMethod("laravelValidationRemote", function (value, element, params) {

<snip code>


			var tokenCSRF = $(validator.currentForm).find('input[name="_token"]').val();

			var formMethod = $(validator.currentForm).attr('method');
            if($(validator.currentForm).find('input[name="_method"]').length) {
                formMethod = $(validator.currentForm).find('input[name="_method"]').val();
            }

            $.ajax( $.extend( true, {
                mode: "abort",
                port: "validate" + element.name,
                dataType: "json",
                data: data,
                context: validator.currentForm,
                url: $(validator.currentForm).attr('action'),
                type: formMethod,

                beforeSend: function (xhr) {
                    if ($(validator.currentForm).attr('method').toLowerCase() !== 'get' && token) {
                        return xhr.setRequestHeader('X-CSRF-TOKEN', tokenCSRF);
                    }
                }
```

I grab the token from the form and then send a simple `X-CSRF-TOKEN` header rather than a `X-XSRF-TOKEN`.

Just curious. I'm sure my way is bad, but I don't know why!

**Comment by torrentalle** [comment]
Hi, 
I'm getting the token from `sessionStore` to avoid requirements in the view code. In this way the library allows to developer use the CSRF token in any manner.
Another reseason is that I'm more comfortable coding in PHP than Javascript.

I will write an improvement to use `X-CSRF-TOKEN` instead of `X-XSRF-TOKEN` in case that `encrypter` is not defined

Sorry for late response, past week I was a litle busy

**Comment by bytestream** [comment]
Due to the volume of issues I'm afraid I'm closing this issue due to lack of activity. This avoids fellow collaborators wasting time investigating this issue, and also prevents giving a false impression that it will eventually be addressed.

To the reporter, please reopen if you still encounter this on the latest version providing a minimal test case. You can also contribute directly by submitting a PR. 

Thanks.
